logging:
  level:
    root: debug
    io.kuark.xxx: debug


kuark:
  ability:
    # 注册中心
    discovery:
      enabled: false
    # 配置中心，开启时，注册中心自动为true
    config:
      enabled: false
    # 缓存
    cache:
      enabled: false


spring:
  profiles:
    active: context-dev
