logging:
  level:
    root: debug
    org.kuark.xxx: debug

nacos:
  test: 999999
  config:
    enabled: false
    server-addr: "127.0.0.1:8848"
    context-path: nacos

context:
  listener:
    classes: org.kuark.config.spring.LocalEnvironmentPrepareEventListener
