logging:
  level:
    root: debug
    io.kuark.xxx: debug

spring:
    redis:
#      url: redis://user:@localhost:6379 # 连接URL，如: redis://user:password@example.com:6379
      host: 127.0.0.1
      port: 6379
      password:
      database: 0 # 使用数据库的索引编号，一个示例有16个数据库 0 到 15
      ssl: false
      max-active: -1
      max-idle: 10
      max-wait: -1ms
      min-idle: 0
      timeout: 3000 # 连接超时时间（毫秒）
#      cluster:
#        max-redirects:  # 集群模式下，集群最大转发的数量
#        nodes: # 集群模式下，逗号分隔的键值对（主机：端口）形式的服务器列表
#      sentinel:
#        master: # 哨兵模式下，Redis主服务器地址
#        nodes: # 哨兵模式下，逗号分隔的键值对（主机：端口）形式的服务器列表
      lettuce:
        pool: # 该配置需要依赖commons-pool2
          max-active: -1 # 连接池最大连接数（负值表示没有限制）
          max-wait: -1 # 连接池最大阻塞等待时间（负值表示没有限制）
          max-idle: 10 # 连接池中的最大空闲连接
          min-idle: 0 # 连接池中的最小空闲连接
          timeout: 3000 # 连接超时时间（毫秒）

redis:
  cluster:
    enabled: false