logging:
  level:
    root: debug
    io.kuark.xxx: debug


spring:
  profiles:
    active: context-test,cache-test
  redis:
    redisson:
      # 配置单点模式
      config: classpath:distributed-lock-single-dev.yml
