logging:
  level:
    root: debug
    io.kuark.xxx: debug
    io:
      seata: info


spring:
  application:
    name: tx
  datasource:
    auto-commit: true

#    platform: h2
#    username: sa
#    password:
#    url: "jdbc:h2:tcp://localhost:9092/./h2/h2;DATABASE_TO_LOWER=TRUE;"
#    driver-class-name: org.h2.Driver

    platform: postgresql
    username: postgres
    password: postgres
    url: "jdbc:postgresql://192.168.0.200:5432/kuark"
    driver-class-name: org.postgresql.Driver
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group

feign:
  hystrix:
    enabled: true
  httpclient:
    connection-timeout: 30000


hystrix:
  command:
    default:
      circuitBreaker:
        sleepWindowInMilliseconds: 100000
        forceClosed: true
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
  shareSecurityContext: true
