logging:
  level:
    root: debug
    io.kuark.xxx: debug
    io:
      seata: info

spring:
  application:
    name: branch-tx1
  datasource:
    auto-commit: true

    #    platform: h2
    #    username: sa
    #    password:
    #    url: "jdbc:h2:tcp://localhost:9092/./h2/h2;DATABASE_TO_LOWER=TRUE;"
    #    driver-class-name: org.h2.Driver

    platform: postgresql
    username: postgres
    password: postgres
    url: "jdbc:postgresql://192.168.0.200:5432/kuark"
    driver-class-name: org.postgresql.Driver
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group

server:
  port: 8181

feign:
  hystrix:
    enabled: true

#seata:
#  enabled: true
#  application-id: branch-tx1
#  tx-service-group: "my_test_tx_group"
##  enable-auto-data-source-proxy: true
##  use-jdk-proxy: false
#  service:
#    vgroup-mapping.my_test_tx_group: default
##    grouplist.default=127.0.0.1:8091
#    enable-degrade: false
#    disable-global-transaction: false
