logging:
  level:
    root: debug
    org.kuark.xxx: debug

cache:
  config:
    enabled: true
    strategy: LOCAL_REMOTE # SINGLE_LOCAL，REMOTE，LOCAL_REMOTE三选一

spring:
  cache:
    caffeine:
      spec: maximumSize=500, expireAfterAccess=3600s