spring:
    redis:
#      url: redis://user:@localhost:6379 # 连接URL，如: redis://user:password@example.com:6379
      host: 127.0.0.1
      port: 6379
      password:
      database: 0 # 使用数据库的索引编号，一个示例有16个数据库 0 到 15