server:
  port: 9201


service-url:
  user-service: http://localhost:8201


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/


logging:
  level:
    org.springframework.cloud.gateway: debug